"""add time to FoodItem

Revision ID: 9d092623c464
Revises: 
Create Date: 2025-04-13 11:52:42.056750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d092623c464'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('food_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time', sa.Time(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('food_item', schema=None) as batch_op:
        batch_op.drop_column('time')

    # ### end Alembic commands ###
