"""add protein to food items

Revision ID: bb5a4de08d9c
Revises: 65ac7e6b6420
Create Date: 2025-04-26 22:24:25.167054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb5a4de08d9c'
down_revision = '65ac7e6b6420'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('food_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('protein', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('food_item', schema=None) as batch_op:
        batch_op.drop_column('protein')

    # ### end Alembic commands ###
